In [1]:
import pandas as pd
import requests

In [2]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [3]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [5]:
temp_df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,26.2504,8.712,28487
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,28.2944,8.687,21577
2,803796,KPop Demon Hunters,"When K-pop superstars Rumi, Mira and Zoey aren...",2025-06-20,284.6079,8.599,334
3,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,15.3842,8.571,13032
4,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,13.0808,8.564,16512

In [6]:
df = pd.DataFrame()

In [7]:
df

Empty DataFrame
Columns: []
Index: []

In [11]:
for i in range(1,429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = df.append(temp_df,ignore_index=True)

In [12]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,26.2504,8.712,28487
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,28.2944,8.687,21577
2,803796,KPop Demon Hunters,"When K-pop superstars Rumi, Mira and Zoey aren...",2025-06-20,284.6079,8.599,334
3,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,15.3842,8.571,13032
4,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,13.0808,8.564,16512
...,...,...,...,...,...,...,...
8555,184125,Assault on Wall Street,Jim is an average New Yorker living a peaceful...,2013-06-30,1.6377,5.882,476
8556,54540,Beverly Hills Chihuahua 2,Puppy mayhem turns the lives of newlywed Chihu...,2011-02-01,1.8678,5.900,400
8557,27414,"Silent Night, Deadly Night","Billy Chapman, who was traumatized by his pare...",1984-11-09,1.3365,5.900,385
8558,780154,All My Friends Are Dead,A group of friends at a New Year’s Eve party g...,2020-12-28,1.0013,5.900,356
8559,650783,The Comeback Trail,Two movie producers who owe money to the mob s...,2020-11-12,1.5831,5.881,333

In [13]:
df.shape

(8560, 7)

In [23]:
df.to_csv('movies.csv')